### ISSUE TITLE
Error while loading shared libraries: libpng12.so.0

### ISSUE THREAD

**Issue by morfikov** [rom1nux/mtkimg#2]
There's no file `libpng12.so.0` on Debian sid. I think it's a little bit old because in the system I can find the package `libpng16-16` which has the the following files:

```
/usr/lib/x86_64-linux-gnu/libpng16.so.16.25.0
/usr/lib/x86_64-linux-gnu/libpng16.so.16
```

**Comment by rom1nux** [comment]
Hello morfikov,
It's probably too late :) but you can rebuild the tool yourself. Take a look in the readme file
